---
- name: update user password
  hosts: xip43
  tasks:
  - user:
      name: "{{ user }}" # 패스워드 변경할 계정 이름을 여기에 입력하면 된다. 
      update_password: always 
      password: "{{ newpassword | password_hash('sha512') }}"
...
