# ansible-playbook db_backup_script_run.yaml

--- 
- name: "Database Backup with sftp" 
  hosts: xipServers
  gather_facts: true
  remote_user: root
  vars: 
     local_path: /root/script
     remote_path: /root/script
  tasks:
    - name: Create a script directory if it does not exist
      become: yes
      file:
        owner: root
        group: root
        path: /root/script
        state: directory
        mode: 0777

    - name: "Script Send" 
      copy: 
        src: "{{ local_path }}/db_backup_sftp.sh" 
        dest: "{{ remote_path }}/db_backup_sftp.sh" 
        owner: root
        group: root
        mode: '0755'  
    
    - name: "Script run"  
      shell: 
        cmd:  |
            {{ remote_path }}/db_backup_sftp.sh
      register: backupScriptRun
      
    - name: "Print Script Run Result"
      debug:  
        var: backupScriptRun.stdout_lines
...
